<?php
namespace app\controller;
use think\Controller;
use think\facade\Env;

class Index extends Controller
{
    //初始化
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //echo 'init';
    }

    public function index()
    {
        return '单一模块！'.Env::get('app_path');
    }

    public function test()
    {
        return '测试类！';
    }

    public function arr()
    {
        $data = array('a'=>1, 'b'=>2, 'c'=>3);
        return json($data);
    }

    public function abc()
    {
        return view();
    }

}
