<?php
namespace app\controller;
use app\model\User as UserModel;
use think\Controller;
use think\Db;
use think\db\exception\DataNotFoundException;

class DataTest extends Controller
{
    public function initialize()
    {
        //parent::initialize(); // TODO: Change the autogenerated stub
        Db::event('before_select', function ($query) {
            echo '批量查询被触发！';
        });

        Db::event('before_find', function ($query) {
            echo '单条查询被触发！';
        });
    }

    public function index()
    {
        $data = Db::table('tp_user')->find();
        //$data = Db::table('tp_user')->where('id', 27)->find();
        //$data = Db::table('tp_user')->where('id', 127)->find();
        //try {
        //    $data = Db::table('tp_user')->where('id', 127)->findOrFail();
        //} catch (DataNotFoundException $e) {
        //    return '查询不到数据！';
        //}
        //$data = Db::table('tp_user')->where('id', 127)->findOrEmpty();
        //$data = Db::table('tp_user')->select();
        //$data = Db::table('tp_user')->where('id', 127)->selectOrFail();
        //$data = Db::table('tp_user')->where('id', 27)->selectOrFail();
        //$data = Db::name('user')->select();
        //$data = \db('user')->selectOrFail();
        //$data = Db::name('user')->where('id', 27)->value('username');
        //$data = Db::name('user')->column('username', 'id');


        //print_r(Db::name('user')->where('id', 27)->order('id', 'desc')->find());
        //$data1 = Db::name('user')->where('id', 27)->order('id', 'desc')->find();
        //$data2 = Db::name('user')->select();
        //$user = Db::name('user');
        //$data1 = $user->where('id',27)->order('id', 'desc')->find();
        //$data2 = $user->removeOption('where')->removeOption('order')->select();
        //return Db::getLastSql();
        //return json($data);
    }

    public function insert()
    {
        $data = [
            'username'      =>      '辉夜',
            'password'      =>      '123',
            'gender'        =>      '女',
            'email'         =>      'huiye@163.com',
            'price'         =>      90,
            'details'       =>      '123',
            'create_time'   =>      date('Y-m-d H:i:s')
        ];

        //$insert = Db::name('user')->insert($data);
        //$insert = Db::name('user')->data($data)->insert();
        //$insert = Db::name('user')->insert($data, true);

        return Db::getLastInsID();
        //return Db::getLastSql();
        return $insert;
    }

    public function insertAll()
    {
        $dataAll = [
            [
                'username'      =>      '辉夜1',
                'password'      =>      '123',
                'gender'        =>      '女',
                'email'         =>      'huiye@163.com',
                'price'         =>      90,
                'details'       =>      '123',
                'create_time'   =>      date('Y-m-d H:i:s')
            ],
            [
                'username'      =>      '辉夜2',
                'password'      =>      '123',
                'gender'        =>      '女',
                'email'         =>      'huiye@163.com',
                'price'         =>      90,
                'details'       =>      '123',
                'create_time'   =>      date('Y-m-d H:i:s')
            ]
        ];

        Db::name('user')->insertAll($dataAll);
    }

    public function update()
    {
        $data = [
            'id'            =>      76,
            'username'      =>      '李白',
            'email'         =>      Db::raw('UPPER(email)'),
            'price'         =>      Db::raw('price - 3')
        ];

        //Db::name('user')->where('id', 73)->update($data);
        //Db::name('user')->where('id', 74)->data($data)->update(['password'=>'456']);
        //Db::name('user')->inc('price', 3)->update($data);
        //Db::name('user')->dec('price', 3)->update($data);
        //Db::name('user')->exp('email', 'UPPER(email)')->update($data);
        //Db::name('user')->update($data);

        //Db::name('user')->where('id', 77)->setField('username', '李白');

        UserModel::update($data);
    }

    public function delete()
    {
        //Db::name('user')->delete(73);
        //Db::name('user')->delete([74,75,76,77]);
        //Db::name('user')->where('id', 78)->delete();
    }

    public function getNoModelData()
    {
        //$data = Db::table('tp_user')->select();
        $data = Db::name('user')->select();
        return json($data);
    }

    public function getModelData()
    {
        $data = User::select();
        //return json($data);
    }
}